### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bfelbo** [akarlsten/cuberun#6]
Awesome project, really well-deserved that it won React Open Source Awards! Would love to play around with this and use it as inspiration for other projects, but there's no license. Have you considered adding a license, e.g. MIT? :)

Would of course attribute you and this repo if making anything inspired by this codebase.

**Comment by akarlsten** [comment]
Done! It was always meant to be MIT, but I never got around to it 😊

**Comment by bfelbo** [comment]
Awesome, thanks!
